config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'prototypes#index'
  resources :prototypes do
    resources :comments, only: [:create]
  end
  resources :users, only: :show
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prototype
  
  validates :text, presence: true
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  has_many :comments
  belongs_to :user
  has_one_attached :image
  
  validates :consept, presence: true
  validates :title, presence: true
  validates :catch, presence: true
  validates :image, presence: true
  # , unless: :was_attached?

  # def was_attached?
    # self.image.attached?
    # image_path = Rails.root.join("tmp", "sample.png")
    
    # article = Article.first
    # File.open(image_path) do |io|
      # article.image.attach(io: io, filename: "sample.png")
    # end
    # article.save!
  # end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true 
         validates :profile, presence: true
         validates :occupation, presence: true
         validates :position, presence: true


         has_many :comments
         has_many :prototypes
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to prototype_path(@comment.prototype) # 今回の実装には関係ありませんが、このようにPrefixでパスを指定することが望ましいです。
    else
      @prototype = @comment.prototype
      @comments = @prototype.comments
      render "prototypes/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototypes, only: [:edit, :show]
  before_action :move_to_index, only: [:edit]
 

  def index
    @prototypes = Prototype.all
    # Prototypeはモデル
    # @prototypesはインスタンス変数
  end


  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
    redirect_to action: :index
    else
    redirect_to action: :new
    end
  end

  def destroy
    prototype = Prototype.find(params[:id])
    prototype.destroy
    redirect_to action: :index
  end

  def edit
    # @prototype= Prototype.find(params[:id])
  #   if  prototype.edit(prototype_params)
  #     redirect_to action: :index
  #   else render :edit
  #  end
  end

 
  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.update(prototype_params)
      redirect_to prototype_path
    else
      render :edit
    end
  end


  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
    @prototype = Prototype.find(params[:id])
  end

  def search
    @prototypes = SearchprototypesService.search(params[:keyword])
  end

  private

  def prototype_params
    params.require(:prototype).permit(:consept, :title, :catch, :image).merge(user_id: current_user.id)
  end

  def set_prototypes
    @prototype = Prototype.find(params[:id])
  end

  def move_to_index
    prototype = Prototype.find(params[:id])
    unless user_signed_in? && current_user.id == prototype.user_id
      redirect_to action: :index 
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.name
    @prototypes = @user.prototypes
  end

  private

  def user_params
    params.require(:user, :name).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
          <%# ログインしているときは以下を表示するようにしましょう %>
            <div class="user_nav grid-6">
              <a class="nav__logout" rel="nofollow" data-method="delete" href="/users/sign_out">ログアウト</a>
              <a class="nav__btn" href="/prototypes/new">New Proto</a>
            </div>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
          <% else %>
            <div class="grid-6">
              <%= link_to "ログイン", new_user_session_path, class: "nav__btn" %>
              <%= link_to "新規登録", new_user_registration_path, class: "nav__btn" %>
            </div>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
         <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with(model: @prototype, local: true) do |form| %>
  <%# <%= form.text_field :image, placeholder: "Image Url" %>
<%# text_field を変更する　（chatapp _main_chat） %>
<%# <form enctype="multipart/form-data" action="/prototypes" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="F+etNwGM0euUWIU8r2jPN+HO3sdLyNZBINWmLY0Jp2WCyN1GPMevp/JZ91mbJaDtDgaoxXcqA91+6P7L8P0/IA=="> %>
  <div class="field">
    <%= form.label :title, "プロトタイプの名称" %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :catch, "キャッチコピー" %><br>
    <%= form.text_area :catch, class: :form__text %>  
  </div>

  <div class="field">
    <%= form.label :consept, "コンセプト" %><br>
    <%= form.text_area :consept, class: :form__text %>
  </div>

  <div class="field">
    <%= form.label :image, "プロトタイプの画像" %><br>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit "保存する", class: :form__btn %>
  </div>
</form>

<%# <%= form.text_area :text, placeholder: "text", rows: "10" %>
<%# <%= form.submit "SEND" %> 
<% end %> 

<%# 見本のアプリを見ながら必要なフォームを作る　ヒントは検証ツール %>
<%# フォームのキー　＆コントローラーのキー　＆モデルのバリデーションのキー  %>







<%# <div class="field">
    <label for="prototype_title">プロトタイプの名称</label><br>
    <input type="text" name="prototype[title]" id="prototype_title">
  </div>

  <div class="field">
    <label for="prototype_catch">キャッチコピー</label><br>
    <textarea class="form__text" name="prototype[catch]" id="prototype_catch"></textarea>
  </div>

  <div class="field">
    <label for="prototype_consept">コンセプト</label><br>
    <textarea class="form__text" name="prototype[consept]" id="prototype_consept"></textarea>
  </div>

  <div class="field">
    <label for="prototype_image">プロトタイプの画像</label><br>
    <input type="file" name="prototype[image]" id="prototype_image">
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="保存する" class="form__btn" data-disable-with="保存する">
  </div>
</form> %>

app/views/prototypes/_prototype.html.erb
<div class="card">
   <%= link_to image_tag(prototype.image,class: :card__img ), prototype_path(prototype) %>
  <div class="card__body">
    <%# <%= link_to "prototype__wrapper", root_path, class: :prototypes%>
    <%# <p class="card__summary"> %>
      <%# <%= "prototype__user" %> 
    <%# </p> %>
    <%# <%= link_to "by user__wrapper", root_path, class: :users_id %>
        <div class="prototype-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= prototype.user.name %>
    </div>
    <div class="prototype-date">
      <!-- 投稿した時刻を出力する -->
      <%# <%= prototype.created_at %> 
    </div>
  </div>
  <div class="lower-prototype">
    <div class="prototype-consept">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= prototype.consept %>
      <%# <%= image_tag prototype.image, class: 'prototype-image' if prototype.image.attached? %>
    </div>
    <%= link_to "by #{prototype.user.name}", user_path(prototype.user), class: :card__user %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# <%= link_to current_prototype.name, edit_prototype_path(current_prototype) %>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form",  locals: { edit_prototype_path: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
<div class="inner">
<%# ログインしているときは以下を表示する %>
<% if user_signed_in? %>
<div class="greeting"> 
こんにちは、
<%= link_to "#{current_user.name}さん", "/users/#{current_user.id}", class: :greeting__link %> 
</div> 
<% end %>
<%# // ログインしているときは上記を表示する %>
<%# <div class="card__wrapper">  %>
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <div class="card__wrapper">
      <%= render partial: 'prototypes/prototype', collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%# <%= form_with(model: @prototype, local: true) do |prototype| %> 
        <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user.id), class: :prototype__user, method: :get %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
         <% if user_signed_in? && current_user.id == @prototype.user_id %>
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), class: :prototype__btn, method: :delete %>
         <% end %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.consept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if current_user %>
          <%= form_with(model: [@prototype, @comment], local: true) do |form| %>
            <%# <%= form.text_area :text%>
            <%# <%= form.label :text, "コメント"%>
            <%# <%= form.text_field :text %>
            <div class="field">
              <label for="comment_text">コメント</label><br>
              <input type="text" name="comment[text]" id="comment_text">
            </div>
            <div class="actions">
            <%= form.submit "SEND", class: :form__btn %>
            </div> 
          <%end%>
        <% else %>
          <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
        <% end %>
          <%# <%= form_with(model: [@prototype, @comment], local: true) do |f|%>
            <%# <div class="field"> %>
            <%# <%= f.label :text, "コメント"<br /> %>
            <%# <%= f.text_field :text %>
            <%# </div> %>
            <%# <div class="actions"> %>
            <%# <%= f.submit "送信する", class: :form__btn  %>
            <%# </div> %>
          <%# <% end %> 
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% if user_signed_in? %>
            <% @comments.each do |comment|%>
            <li>
              <%=  comment.text %>
              <%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %>
            <% end %>
          <%end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
          <%# <div class="container">
            
            <% if current_user %>
              <%# <%= form_with(model: [@prototype, @comment], local: true) do |form| %>
              <%# <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
              <%# <%= form.submit "SEND" %>
          <%# <% end %>
          <%# <% else %>
            <%# <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong> %>
        <%# <% end %>
          <%# <div class="comments"> %>
            <%# <h4>＜コメント一覧＞</h4> %>
            <%# <% if @comments %>
              <%# <% @comments.each do |comment| %>
               <%# <p> %>
                 <%# <strong><%= link_to comment.user.name, "/users/#{comment.user_id}"：</strong> %>
                <%# <%= comment.text %>
              <%# </p> %>
              <%# <% end %>
            <%# <% end %>
    </div>
    </div>
  </div>
        
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @user.name%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= link_to "#{@user.name}さんのプロトタイプ" %>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: "prototypes/prototype", collection: @user.prototypes %>
      </div>
    </div>
  </div>
</div>